package cn.lex_mung.client_android.app;

public class BundleTags {
    public static final String TYPE = "type";
    public static final String URL = "url";
    public static final String IS_SHARE = "is_share";
    public static final String TITLE = "title";
    public static final String DES = "des";
    public static final String IMAGE = "image";
    public static final String BALANCE = "balance";
    public static final String OPERATION = "operation";
    public static final String ID = "id";
    public static final String MEMBER_ID = "member_id";
    public static final String L_MEMBER_ID = "l_member_id";
    public static final String LIST = "list";
    public static final String LEVEL = "level";
    public static final String REGION_ID = "regionId";
    public static final String CONSULTATION_ID = "consultation_id";
    public static final String LAWYER_ID = "lawyer_id";
    public static final String BASIC_INFO = "basic_info";
    public static final String MEMBER_ROLE_ID = "member_role_id";
    public static final String STATE = "state";
    public static final String ENTITY = "entity";
    public static final String REQUIREMENT_ID = "requirement_id";
    public static final String ORG_ID = "org_id";
    public static final String MONEY = "money";
    public static final String WX = "wx";
    public static final String ZFB = "zfb";
    public static final String ORDER_NO = "order_no";
    public static final String FLAG = "flag";
    public static final String REGION_ID_1 = "REGION_ID_1";
    public static final String REGION_ID_2 = "REGION_ID_2";
    public static final String REQUIRE_TYPE_ID = "requireTypeId";
    public static final String REQUIRE_TYPE_NAME = "requireTypeName";
    public static final String JSON = "json";
    public static final String IS_RECEIVE_REQUIRE_MENT = "is_receive_require_ment";
    public static final String TAGIDS = "tagIds";
    public static final String POSITION = "position";
    public static final String KEY_LAT = "key_lat";
    public static final String KEY_LNG = "key_lng";
    public static final String KEY_TITLE = "key_title";
    public static final String KEY_LEVEL = "key_level";
    public static final String REGION = "region";
    public static final String MOBILE  = "mobile";
    public static final String NUM  = "num";
    public static final String IS_SHOW  = "is_show";
    public static final String SOLUTION_TYPE_ID = "solution_type_id";
    public static final String SOLUTION_TYPE_NAME = "solution_type_name";
    public static final String AMOUNT_ID = "amount_id";
    public static final String CONTENT = "content";
    public static final String BURYING_POINT = "burying_point";
    public static final String BUSINESS_ID = "business_id";
    public static final String BUSINESS_NAME = "business_name";
    public static final String COUPON_ID = "coupon_id";
    public static final String COUPON_TYPE = "coupon_type";

}
